[package]
name = "shadertui"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = "1.23.1"
crossterm = { version = "0.29", features = ["event-stream"] }
flume = "0.11.1"
pollster = "0.4.0"
wgpu = "25.0.2"
